language: rust
rust:
  - stable
  - beta
  - nightly

dist: trusty
sudo: false

cache: cargo

install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-host=$TARGET --default-toolchain=$TRAVIS_RUST_VERSION -y

script:
  - cargo build --verbose
  # Only run the targets if we are on the same OS.
  - if [ "$RUN" == "1" ]; then cargo test --verbose fi
matrix:
  include:
    # Linux
    # 32-bit requires multilib.
    - env: TARGET=i686-unknown-linux-gnu RUN=1
      addons:
        apt:
          packages:
            - gcc-multilib
    # 64-bit works as-is.
    - env: TARGET=x86_64-unknown-linux-gnu RUN=1
    # Mac OS X
    - os: osx
      env: TARGET=i686-apple-darwin RUN=1
    - os: osx
      env: TARGET=x86_64-apple-darwin RUN=1
    # Android
    # - for x86
    - env: TARGET=i686-linux-android
    - env: TARGET=x86_64-linux-android
    # - for ARM
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=aarch64-linux-android
    # IOS
    - os: osx
      osx_image: xcode9
      env: TARGET=i386-apple-ios
    - os: osx
      osx_image: xcode9
      env: TARGET=x86_64-apple-ios
    # BSD derivatives.
    - env: TARGET=x86_64-unknown-freebsd

notifications:
  email: false
