language: rust
rust: stable
dist: trusty
sudo: false

cache: cargo

install:
  - if [ -z "$NO_ADD" ]; then rustup target add "$TARGET"; fi

script:
  - cargo build --verbose --target "$TARGET"
  # Only run the targets if we are on the same OS.
  - if [ "$RUN" == "1" ]; then cargo test --verbose --target "$TARGET"; fi

matrix:
  include:
    # Linux
    # 32-bit requires multilib.
    - env: TARGET=i686-unknown-linux-gnu RUN=1
      addons:
        apt:
          packages:
            - gcc-multilib
    # 64-bit stable.
    - env: TARGET=x86_64-unknown-linux-gnu RUN=1 NO_ADD=1
      rust: stable
    # 64-bit beta.
    - env: TARGET=x86_64-unknown-linux-gnu RUN=1 NO_ADD=1
      rust: beta
    # 64-bit nightly.
    - env: TARGET=x86_64-unknown-linux-gnu RUN=1 NO_ADD=1
      rust: nightly
    # Mac OS X
    - os: osx
      env: TARGET=i686-apple-darwin RUN=1
    - os: osx
      env: TARGET=x86_64-apple-darwin RUN=1 NO_ADD=1
    # Android
    # - for x86
    - env: TARGET=i686-linux-android
    - env: TARGET=x86_64-linux-android
    # - for ARM
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=aarch64-linux-android
    # IOS
    - os: osx
      osx_image: xcode9
      env: TARGET=i386-apple-ios
    - os: osx
      osx_image: xcode9
      env: TARGET=x86_64-apple-ios
    # BSD derivatives.
    - env: TARGET=x86_64-unknown-freebsd

notifications:
  email: false
