language: rust
rust:
  - stable
  - beta
  - nightly

dist: trusty
sudo: false

cache: cargo

install:
  # If no TARGET is set, we are running on Linux, and we are building for stable/beta/nightly Rust.
  - if [ -z "$TARGET" ]; then TARGET="x86_64-unknown-linux-gnu" && RUN="1"; else rustup target add "$TARGET"; fi

script:
  - cargo build --verbose --target "$TARGET"
  # Only run the targets if we are on the same OS.
  - [ "$RUN" == "1" ] && cargo test --verbose --target "$TARGET"

matrix:
  include:
    # Mac OS X
    - os: osx
      env: TARGET=i686-apple-darwin RUN=1
    - os: osx
      # No env variables because we are building and running for this architecture.
    # Android
    # - for x86
    - env: TARGET=i686-linux-android
    - env: TARGET=x86_64-linux-android
    # - for ARM
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=aarch64-linux-android
    # IOS
    - os: osx
      osx_image: xcode9
      env: TARGET=i386-apple-ios
    - os: osx
      osx_image: xcode9
      env: TARGET=x86_64-apple-ios
    # BSD derivatives.
    - env: TARGET=x86_64-unknown-freebsd
    - env: TARGET=x86_64-unknown-openbsd

notifications:
  email: false
